config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # def after_sign_in_path_for(resource)
  #   memories_path
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex align-items-center"
     style="min-height: 100vh;"
     data-controller="start">
  <div class="container pt-2 pb-2">
    <h1 class="text-center">pensine</h1>
    <h2 class="text-center">
      <%= t '.subtitle', default: 'explore your memories' %>
    </h2>
    <% unless user_signed_in? %>
      <div class="d-flex justify-content-center">
        <div class="btn btn-primary"
             data-action="click->start#displaySessionForm"
             data-target="start.startButton">Start</div>
      </div>
      <div class="row justify-content-center">
        <div class="col-10">
          <%= simple_form_for :user, :url => session_path(:user),
            html: {
              class: "d-none",
              data: { target: "start.sessionForm" }
             } do |f| %>
            <%= f.input :email, placeholder: 'albus@pensine.me' %>
            <%= f.input :password, placeholder: '********' %>
            <div class="form-group">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
            <div class="form-group d-flex justify-content-center">
              <%= f.submit 'Connect', class: "btn btn-primary" %>
            </div>
            <div>
              <%= link_to "Forgot your password?", new_password_path(:user) %>
            </div>
            <div>
              <%= link_to t('.sign_up', default: 'No account yet?'), '#',
              data: { action: 'click->start#displayRegistrationForm' } %>
            </div>
          <% end %>
        </div>
        <div class="col-10">
          <%= simple_form_for :user, :url => registration_path(:user),
            html: {
              class: "d-none",
              data: { target: "start.registrationForm"}
             } do |f| %>
            <%= f.input :email, placeholder: 'albus@pensine.me' %>
            <%= f.input :password, placeholder: '********' %>
            <div class="form-group">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
            <div class="form-group d-flex justify-content-center">
              <%= f.submit 'Connect', class: "btn btn-primary" %>
            </div>
            <%= link_to t('.sign_in', default: 'Already have an account?'), '#',
              data: { action: 'click->start#displaySessionForm' } %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>